services:
  # run jupyter notebook inside jupyter
  jupyter-notebook:
    image:  eligoze75/sepsis-survival-minimal-clinical-records:e7e9ba3
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
