name: sepsis_survival_venv
channels:
  - conda-forge
dependencies:
  - pandas=2.3.3
  - jupyterlab=4.4.10
  - python=3.12.12
  - scipy=1.16.3
  - scikit-learn=1.7.2
  - matplotlib=3.10.8
  - seaborn=0.13.2
  - plotly=6.5.0
  - shap=0.48.0
  - black=25.1.0
  - flake8=7.3.0
  - conda-lock
prefix: /Users/eligoze/miniforge3/envs/sepsis_survival_venv
