name: sepsis_survival_venv
channels:
  - conda-forge
dependencies:
  - pandas=2.3.3
  - jupyterlab=4.4.10
  - python=3.12.12
  - scipy=1.16.3
  - scikit-learn=1.7.2
  - matplotlib=3.10.8
  - seaborn=0.13.2
  - plotly=6.5.0
  - shap=0.48.0
  - black=25.1.0
  - flake8=7.3.0
  - conda-lock=3.0.4
  - pandera=0.26.1
  - quarto=1.8.26
  - click=8.3.1
  - tabulate=0.9.0
  - altair=6.0.0
  - vl-convert-python=1.8.0
  - ipykernel=6.24.0
  - pytest=8.4.2
  
prefix: /Users/eligoze/miniforge3/envs/sepsis_survival_venv
